name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: run dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: >
            cd DotNet &&
            dotnet publish -bl:../Native/app/build/outputs/dotnet.binlog &&
            cd .. &&
            cd Native &&
            ./gradlew assembleDebug &&
            ./gradlew assembleRelease

      - name: archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: Native/app/build/outputs
          if-no-files-found: error
